const restaurants = [
  {
    image: "nine",
    name: "Devil Fruit Delights",
    rating: 1,
    food_type: "Ramen",
    Price_for_two: 1869,
    location: "Sabaody Archipelago",
    Distance_from_Customer_house: "9.9",
    offers: 21,
    alcohol: true,
    Restaurant_open_time: 23,
    Restaurant_close_time: 11,
  },
  {
    image: "seven",
    name: "Zoro’s Sushi Den",
    rating: 3,
    food_type: "Matcha Desserts",
    Price_for_two: 1927,
    location: "Impel Down",
    Distance_from_Customer_house: "4.7",
    offers: 8,
    alcohol: true,
    Restaurant_open_time: 11,
    Restaurant_close_time: 23,
  },
  {
    image: "seven",
    name: "Merry Go Meals",
    rating: 1,
    food_type: "Matcha Desserts",
    Price_for_two: 1108,
    location: "Dressrosa",
    Distance_from_Customer_house: "9.6",
    offers: 12,
    alcohol: true,
    Restaurant_open_time: 21,
    Restaurant_close_time: 9,
  },
  {
    image: "second",
    name: "Devil Fruit Delights",
    rating: 1,
    food_type: "Yakitori",
    Price_for_two: 2226,
    location: "Raftel (Laughtale)",
    Distance_from_Customer_house: "1.8",
    offers: 6,
    alcohol: false,
    Restaurant_open_time: 1,
    Restaurant_close_time: 13,
  },
  {
    image: "eight",
    name: "Gomu Gomu Grill",
    rating: 3,
    food_type: "Sushi",
    Price_for_two: 1140,
    location: "Water 7",
    Distance_from_Customer_house: "2.0",
    offers: 28,
    alcohol: true,
    Restaurant_open_time: 9,
    Restaurant_close_time: 21,
  },
  {
    image: "ten",
    name: "Pirate King's Banquet",
    rating: 3,
    food_type: "Onigiri",
    Price_for_two: 1720,
    location: "Whole Cake Island",
    Distance_from_Customer_house: "3.2",
    offers: 18,
    alcohol: false,
    Restaurant_open_time: 6,
    Restaurant_close_time: 18,
  },
  {
    image: "seven",
    name: "Red-Haired Tavern",
    rating: 1,
    food_type: "Ramen",
    Price_for_two: 1574,
    location: "Marineford",
    Distance_from_Customer_house: "4.6",
    offers: 8,
    alcohol: false,
    Restaurant_open_time: 8,
    Restaurant_close_time: 20,
  },
  {
    image: "second",
    name: "Yonko’s Feast",
    rating: 2,
    food_type: "Onigiri",
    Price_for_two: 215,
    location: "Whole Cake Island",
    Distance_from_Customer_house: "3.8",
    offers: 5,
    alcohol: false,
    Restaurant_open_time: 6,
    Restaurant_close_time: 18,
  },
  {
    image: "eight",
    name: "Baratie Bites",
    rating: 1,
    food_type: "Ramen",
    Price_for_two: 2354,
    location: "Impel Down",
    Distance_from_Customer_house: "1.7",
    offers: 8,
    alcohol: false,
    Restaurant_open_time: 7,
    Restaurant_close_time: 19,
  },
  {
    image: "seven",
    name: "Red-Haired Tavern",
    rating: 2,
    food_type: "Udon",
    Price_for_two: 1824,
    location: "Water 7",
    Distance_from_Customer_house: "7.4",
    offers: 13,
    alcohol: false,
    Restaurant_open_time: 15,
    Restaurant_close_time: 3,
  },
  {
    image: "fourth",
    name: "Wano Ramen House",
    rating: 2,
    food_type: "Takoyaki",
    Price_for_two: 1951,
    location: "Foosha Village",
    Distance_from_Customer_house: "1.9",
    offers: 26,
    alcohol: false,
    Restaurant_open_time: 9,
    Restaurant_close_time: 21,
  },
  {
    image: "fourth",
    name: "Luffy’s Meat Paradise",
    rating: 1,
    food_type: "Yakitori",
    Price_for_two: 1982,
    location: "Dressrosa",
    Distance_from_Customer_house: "3.2",
    offers: 18,
    alcohol: true,
    Restaurant_open_time: 2,
    Restaurant_close_time: 14,
  },
  {
    image: "ten",
    name: "Gear 5 Gastro",
    rating: 1,
    food_type: "Onigiri",
    Price_for_two: 1195,
    location: "Foosha Village",
    Distance_from_Customer_house: "7.0",
    offers: 20,
    alcohol: false,
    Restaurant_open_time: 7,
    Restaurant_close_time: 19,
  },
  {
    image: "seven",
    name: "Sky Island Sweets",
    rating: 5,
    food_type: "Sushi",
    Price_for_two: 683,
    location: "Foosha Village",
    Distance_from_Customer_house: "1.8",
    offers: 29,
    alcohol: true,
    Restaurant_open_time: 9,
    Restaurant_close_time: 21,
  },
  {
    image: "nine",
    name: "Merry Go Meals",
    rating: 4,
    food_type: "Sushi",
    Price_for_two: 567,
    location: "Whole Cake Island",
    Distance_from_Customer_house: "8.8",
    offers: 3,
    alcohol: true,
    Restaurant_open_time: 4,
    Restaurant_close_time: 16,
  },
  {
    image: "ten",
    name: "Raftel Resto",
    rating: 2,
    food_type: "Okonomiyaki",
    Price_for_two: 1093,
    location: "Dressrosa",
    Distance_from_Customer_house: "9.6",
    offers: 10,
    alcohol: false,
    Restaurant_open_time: 7,
    Restaurant_close_time: 19,
  },
  {
    image: "seven",
    name: "Wano Ramen House",
    rating: 4,
    food_type: "Onigiri",
    Price_for_two: 1719,
    location: "Impel Down",
    Distance_from_Customer_house: "8.8",
    offers: 2,
    alcohol: false,
    Restaurant_open_time: 3,
    Restaurant_close_time: 15,
  },
  {
    image: "nine",
    name: "Gear 5 Gastro",
    rating: 5,
    food_type: "Okonomiyaki",
    Price_for_two: 2230,
    location: "Whole Cake Island",
    Distance_from_Customer_house: "4.3",
    offers: 17,
    alcohol: false,
    Restaurant_open_time: 15,
    Restaurant_close_time: 3,
  },
  {
    image: "eight",
    name: "Wano Ramen House",
    rating: 5,
    food_type: "Yakitori",
    Price_for_two: 374,
    location: "Foosha Village",
    Distance_from_Customer_house: "6.7",
    offers: 12,
    alcohol: true,
    Restaurant_open_time: 6,
    Restaurant_close_time: 18,
  },
  {
    image: "nine",
    name: "East Blue Eatery",
    rating: 4,
    food_type: "Matcha Desserts",
    Price_for_two: 509,
    location: "Raftel (Laughtale)",
    Distance_from_Customer_house: "9.3",
    offers: 8,
    alcohol: true,
    Restaurant_open_time: 4,
    Restaurant_close_time: 16,
  },
  {
    image: "third",
    name: "Pirate King's Banquet",
    rating: 5,
    food_type: "Katsu Curry",
    Price_for_two: 2395,
    location: "Water 7",
    Distance_from_Customer_house: "10.6",
    offers: 23,
    alcohol: false,
    Restaurant_open_time: 4,
    Restaurant_close_time: 16,
  },
  {
    image: "fourth",
    name: "Straw Hat Café",
    rating: 4,
    food_type: "Yakitori",
    Price_for_two: 1649,
    location: "Skypiea",
    Distance_from_Customer_house: "6.1",
    offers: 16,
    alcohol: false,
    Restaurant_open_time: 1,
    Restaurant_close_time: 13,
  },
  {
    image: "first",
    name: "All Blue Kitchen",
    rating: 4,
    food_type: "Katsu Curry",
    Price_for_two: 1142,
    location: "Impel Down",
    Distance_from_Customer_house: "4.1",
    offers: 10,
    alcohol: true,
    Restaurant_open_time: 9,
    Restaurant_close_time: 21,
  },
  {
    image: "second",
    name: "Sanji’s Gourmet Haven",
    rating: 3,
    food_type: "Ramen",
    Price_for_two: 421,
    location: "Dressrosa",
    Distance_from_Customer_house: "4.2",
    offers: 3,
    alcohol: true,
    Restaurant_open_time: 3,
    Restaurant_close_time: 15,
  },
  {
    image: "second",
    name: "Gear 5 Gastro",
    rating: 2,
    food_type: "Yakitori",
    Price_for_two: 1057,
    location: "Skypiea",
    Distance_from_Customer_house: "10.5",
    offers: 8,
    alcohol: true,
    Restaurant_open_time: 2,
    Restaurant_close_time: 14,
  },
  {
    image: "second",
    name: "All Blue Kitchen",
    rating: 5,
    food_type: "Matcha Desserts",
    Price_for_two: 233,
    location: "Foosha Village",
    Distance_from_Customer_house: "1.7",
    offers: 18,
    alcohol: false,
    Restaurant_open_time: 23,
    Restaurant_close_time: 11,
  },
  {
    image: "nine",
    name: "Sky Island Sweets",
    rating: 4,
    food_type: "Okonomiyaki",
    Price_for_two: 619,
    location: "Wano Country",
    Distance_from_Customer_house: "4.1",
    offers: 3,
    alcohol: true,
    Restaurant_open_time: 3,
    Restaurant_close_time: 15,
  },
  {
    image: "seven",
    name: "Luffy’s Meat Paradise",
    rating: 1,
    food_type: "Katsu Curry",
    Price_for_two: 2011,
    location: "Impel Down",
    Distance_from_Customer_house: "2.0",
    offers: 22,
    alcohol: false,
    Restaurant_open_time: 19,
    Restaurant_close_time: 7,
  },
  {
    image: "ten",
    name: "Sky Island Sweets",
    rating: 2,
    food_type: "Udon",
    Price_for_two: 1405,
    location: "Whole Cake Island",
    Distance_from_Customer_house: "11.0",
    offers: 10,
    alcohol: true,
    Restaurant_open_time: 7,
    Restaurant_close_time: 19,
  },
  {
    image: "seven",
    name: "Devil Fruit Delights",
    rating: 5,
    food_type: "Takoyaki",
    Price_for_two: 1810,
    location: "Foosha Village",
    Distance_from_Customer_house: "10.6",
    offers: 21,
    alcohol: false,
    Restaurant_open_time: 13,
    Restaurant_close_time: 1,
  },
  {
    image: "second",
    name: "Sky Island Sweets",
    rating: 1,
    food_type: "Okonomiyaki",
    Price_for_two: 882,
    location: "Sabaody Archipelago",
    Distance_from_Customer_house: "10.3",
    offers: 15,
    alcohol: false,
    Restaurant_open_time: 19,
    Restaurant_close_time: 7,
  },
  {
    image: "second",
    name: "All Blue Kitchen",
    rating: 5,
    food_type: "Tempura",
    Price_for_two: 1688,
    location: "Dressrosa",
    Distance_from_Customer_house: "7.6",
    offers: 19,
    alcohol: false,
    Restaurant_open_time: 10,
    Restaurant_close_time: 22,
  },
  {
    image: "eight",
    name: "Treasure Island Bistro",
    rating: 4,
    food_type: "Udon",
    Price_for_two: 1503,
    location: "Marineford",
    Distance_from_Customer_house: "9.7",
    offers: 8,
    alcohol: true,
    Restaurant_open_time: 11,
    Restaurant_close_time: 23,
  },
  {
    image: "nine",
    name: "Luffy’s Meat Paradise",
    rating: 5,
    food_type: "Ramen",
    Price_for_two: 184,
    location: "Dressrosa",
    Distance_from_Customer_house: "10.5",
    offers: 10,
    alcohol: false,
    Restaurant_open_time: 22,
    Restaurant_close_time: 10,
  },
  {
    image: "seven",
    name: "Red-Haired Tavern",
    rating: 4,
    food_type: "Katsu Curry",
    Price_for_two: 1047,
    location: "Dressrosa",
    Distance_from_Customer_house: "8.1",
    offers: 25,
    alcohol: true,
    Restaurant_open_time: 2,
    Restaurant_close_time: 14,
  },
  {
    image: "first",
    name: "Straw Hat Café",
    rating: 5,
    food_type: "Takoyaki",
    Price_for_two: 184,
    location: "Dressrosa",
    Distance_from_Customer_house: "4.6",
    offers: 27,
    alcohol: true,
    Restaurant_open_time: 5,
    Restaurant_close_time: 17,
  },
  {
    image: "second",
    name: "Wano Ramen House",
    rating: 3,
    food_type: "Tempura",
    Price_for_two: 290,
    location: "Marineford",
    Distance_from_Customer_house: "5.2",
    offers: 22,
    alcohol: false,
    Restaurant_open_time: 16,
    Restaurant_close_time: 4,
  },
  {
    image: "third",
    name: "Devil Fruit Delights",
    rating: 3,
    food_type: "Okonomiyaki",
    Price_for_two: 1806,
    location: "Foosha Village",
    Distance_from_Customer_house: "8.8",
    offers: 22,
    alcohol: false,
    Restaurant_open_time: 17,
    Restaurant_close_time: 5,
  },
  {
    image: "ten",
    name: "Sanji’s Gourmet Haven",
    rating: 1,
    food_type: "Tempura",
    Price_for_two: 1192,
    location: "Raftel (Laughtale)",
    Distance_from_Customer_house: "5.3",
    offers: 21,
    alcohol: false,
    Restaurant_open_time: 19,
    Restaurant_close_time: 7,
  },
  {
    image: "ten",
    name: "East Blue Eatery",
    rating: 2,
    food_type: "Sushi",
    Price_for_two: 1361,
    location: "Water 7",
    Distance_from_Customer_house: "5.5",
    offers: 30,
    alcohol: false,
    Restaurant_open_time: 1,
    Restaurant_close_time: 13,
  },
  {
    image: "fourth",
    name: "East Blue Eatery",
    rating: 2,
    food_type: "Udon",
    Price_for_two: 201,
    location: "Whole Cake Island",
    Distance_from_Customer_house: "9.7",
    offers: 17,
    alcohol: false,
    Restaurant_open_time: 13,
    Restaurant_close_time: 1,
  },
  {
    image: "ten",
    name: "Sanji’s Gourmet Haven",
    rating: 3,
    food_type: "Katsu Curry",
    Price_for_two: 2341,
    location: "Whole Cake Island",
    Distance_from_Customer_house: "7.1",
    offers: 3,
    alcohol: false,
    Restaurant_open_time: 0,
    Restaurant_close_time: 12,
  },
  {
    image: "second",
    name: "Sky Island Sweets",
    rating: 1,
    food_type: "Onigiri",
    Price_for_two: 1007,
    location: "Marineford",
    Distance_from_Customer_house: "10.5",
    offers: 5,
    alcohol: true,
    Restaurant_open_time: 18,
    Restaurant_close_time: 6,
  },
  {
    image: "third",
    name: "Baratie Bites",
    rating: 4,
    food_type: "Tempura",
    Price_for_two: 308,
    location: "Raftel (Laughtale)",
    Distance_from_Customer_house: "3.3",
    offers: 20,
    alcohol: true,
    Restaurant_open_time: 5,
    Restaurant_close_time: 17,
  },
  {
    image: "nine",
    name: "Grand Line Diner",
    rating: 5,
    food_type: "Onigiri",
    Price_for_two: 2238,
    location: "Water 7",
    Distance_from_Customer_house: "6.3",
    offers: 15,
    alcohol: false,
    Restaurant_open_time: 10,
    Restaurant_close_time: 22,
  },
  {
    image: "eight",
    name: "Grand Line Diner",
    rating: 3,
    food_type: "Onigiri",
    Price_for_two: 1434,
    location: "Wano Country",
    Distance_from_Customer_house: "1.1",
    offers: 3,
    alcohol: true,
    Restaurant_open_time: 11,
    Restaurant_close_time: 23,
  },
  {
    image: "nine",
    name: "Baratie Bites",
    rating: 1,
    food_type: "Okonomiyaki",
    Price_for_two: 143,
    location: "Impel Down",
    Distance_from_Customer_house: "9.9",
    offers: 0,
    alcohol: false,
    Restaurant_open_time: 7,
    Restaurant_close_time: 19,
  },
  {
    image: "seven",
    name: "Merry Go Meals",
    rating: 3,
    food_type: "Ramen",
    Price_for_two: 1940,
    location: "Sabaody Archipelago",
    Distance_from_Customer_house: "6.1",
    offers: 0,
    alcohol: false,
    Restaurant_open_time: 12,
    Restaurant_close_time: 0,
  },
  {
    image: "third",
    name: "Red-Haired Tavern",
    rating: 4,
    food_type: "Onigiri",
    Price_for_two: 1341,
    location: "Sabaody Archipelago",
    Distance_from_Customer_house: "7.9",
    offers: 7,
    alcohol: true,
    Restaurant_open_time: 2,
    Restaurant_close_time: 14,
  },
  {
    image: "fifth",
    name: "Raftel Resto",
    rating: 2,
    food_type: "Udon",
    Price_for_two: 2356,
    location: "Impel Down",
    Distance_from_Customer_house: "5.9",
    offers: 23,
    alcohol: true,
    Restaurant_open_time: 15,
    Restaurant_close_time: 3,
  },
  {
    image: "eight",
    name: "Gear 5 Gastro",
    rating: 2,
    food_type: "Yakitori",
    Price_for_two: 2008,
    location: "Impel Down",
    Distance_from_Customer_house: "8.2",
    offers: 20,
    alcohol: true,
    Restaurant_open_time: 12,
    Restaurant_close_time: 0,
  },
  {
    image: "second",
    name: "Straw Hat Café",
    rating: 1,
    food_type: "Yakitori",
    Price_for_two: 2281,
    location: "Foosha Village",
    Distance_from_Customer_house: "9.2",
    offers: 10,
    alcohol: false,
    Restaurant_open_time: 15,
    Restaurant_close_time: 3,
  },
  {
    image: "seven",
    name: "Red-Haired Tavern",
    rating: 2,
    food_type: "Katsu Curry",
    Price_for_two: 1520,
    location: "Whole Cake Island",
    Distance_from_Customer_house: "3.7",
    offers: 19,
    alcohol: false,
    Restaurant_open_time: 3,
    Restaurant_close_time: 15,
  },
  {
    image: "nine",
    name: "Devil Fruit Delights",
    rating: 3,
    food_type: "Udon",
    Price_for_two: 1926,
    location: "Foosha Village",
    Distance_from_Customer_house: "3.0",
    offers: 11,
    alcohol: false,
    Restaurant_open_time: 9,
    Restaurant_close_time: 21,
  },
  {
    image: "ten",
    name: "Wano Ramen House",
    rating: 3,
    food_type: "Onigiri",
    Price_for_two: 1298,
    location: "Skypiea",
    Distance_from_Customer_house: "8.7",
    offers: 14,
    alcohol: true,
    Restaurant_open_time: 15,
    Restaurant_close_time: 3,
  },
  {
    image: "first",
    name: "Red-Haired Tavern",
    rating: 5,
    food_type: "Sushi",
    Price_for_two: 326,
    location: "Marineford",
    Distance_from_Customer_house: "6.5",
    offers: 22,
    alcohol: false,
    Restaurant_open_time: 16,
    Restaurant_close_time: 4,
  },
  {
    image: "nine",
    name: "Sunny Feast",
    rating: 3,
    food_type: "Sushi",
    Price_for_two: 887,
    location: "Raftel (Laughtale)",
    Distance_from_Customer_house: "5.4",
    offers: 6,
    alcohol: false,
    Restaurant_open_time: 4,
    Restaurant_close_time: 16,
  },
  {
    image: "ten",
    name: "Sunny Feast",
    rating: 3,
    food_type: "Yakitori",
    Price_for_two: 1513,
    location: "Whole Cake Island",
    Distance_from_Customer_house: "10.1",
    offers: 20,
    alcohol: false,
    Restaurant_open_time: 9,
    Restaurant_close_time: 21,
  },
  {
    image: "fifth",
    name: "Devil Fruit Delights",
    rating: 3,
    food_type: "Onigiri",
    Price_for_two: 222,
    location: "Water 7",
    Distance_from_Customer_house: "5.2",
    offers: 19,
    alcohol: false,
    Restaurant_open_time: 20,
    Restaurant_close_time: 8,
  },
  {
    image: "fifth",
    name: "Red-Haired Tavern",
    rating: 4,
    food_type: "Takoyaki",
    Price_for_two: 271,
    location: "Skypiea",
    Distance_from_Customer_house: "9.5",
    offers: 13,
    alcohol: false,
    Restaurant_open_time: 8,
    Restaurant_close_time: 20,
  },
  {
    image: "third",
    name: "Gear 5 Gastro",
    rating: 1,
    food_type: "Okonomiyaki",
    Price_for_two: 132,
    location: "Raftel (Laughtale)",
    Distance_from_Customer_house: "4.7",
    offers: 12,
    alcohol: false,
    Restaurant_open_time: 17,
    Restaurant_close_time: 5,
  },
  {
    image: "seven",
    name: "Raftel Resto",
    rating: 2,
    food_type: "Onigiri",
    Price_for_two: 1392,
    location: "Whole Cake Island",
    Distance_from_Customer_house: "9.0",
    offers: 15,
    alcohol: false,
    Restaurant_open_time: 10,
    Restaurant_close_time: 22,
  },
  {
    image: "ten",
    name: "Red-Haired Tavern",
    rating: 3,
    food_type: "Tempura",
    Price_for_two: 441,
    location: "Marineford",
    Distance_from_Customer_house: "8.8",
    offers: 14,
    alcohol: false,
    Restaurant_open_time: 8,
    Restaurant_close_time: 20,
  },
  {
    image: "seven",
    name: "Sanji’s Gourmet Haven",
    rating: 5,
    food_type: "Matcha Desserts",
    Price_for_two: 1901,
    location: "Marineford",
    Distance_from_Customer_house: "1.3",
    offers: 13,
    alcohol: false,
    Restaurant_open_time: 2,
    Restaurant_close_time: 14,
  },
  {
    image: "seven",
    name: "Grand Line Diner",
    rating: 5,
    food_type: "Udon",
    Price_for_two: 1611,
    location: "Water 7",
    Distance_from_Customer_house: "7.7",
    offers: 3,
    alcohol: false,
    Restaurant_open_time: 3,
    Restaurant_close_time: 15,
  },
  {
    image: "third",
    name: "Wano Ramen House",
    rating: 4,
    food_type: "Katsu Curry",
    Price_for_two: 851,
    location: "Dressrosa",
    Distance_from_Customer_house: "3.8",
    offers: 1,
    alcohol: true,
    Restaurant_open_time: 7,
    Restaurant_close_time: 19,
  },
  {
    image: "second",
    name: "Baratie Bites",
    rating: 3,
    food_type: "Yakitori",
    Price_for_two: 1674,
    location: "Whole Cake Island",
    Distance_from_Customer_house: "5.2",
    offers: 10,
    alcohol: false,
    Restaurant_open_time: 10,
    Restaurant_close_time: 22,
  },
  {
    image: "ten",
    name: "Gear 5 Gastro",
    rating: 5,
    food_type: "Sushi",
    Price_for_two: 319,
    location: "Wano Country",
    Distance_from_Customer_house: "4.8",
    offers: 10,
    alcohol: true,
    Restaurant_open_time: 2,
    Restaurant_close_time: 14,
  },
  {
    image: "fifth",
    name: "Gear 5 Gastro",
    rating: 5,
    food_type: "Okonomiyaki",
    Price_for_two: 1045,
    location: "Wano Country",
    Distance_from_Customer_house: "3.0",
    offers: 16,
    alcohol: true,
    Restaurant_open_time: 5,
    Restaurant_close_time: 17,
  },
  {
    image: "seven",
    name: "Baratie Bites",
    rating: 2,
    food_type: "Matcha Desserts",
    Price_for_two: 1147,
    location: "Water 7",
    Distance_from_Customer_house: "7.0",
    offers: 4,
    alcohol: true,
    Restaurant_open_time: 11,
    Restaurant_close_time: 23,
  },
  {
    image: "first",
    name: "Straw Hat Café",
    rating: 4,
    food_type: "Sushi",
    Price_for_two: 585,
    location: "Foosha Village",
    Distance_from_Customer_house: "5.1",
    offers: 5,
    alcohol: true,
    Restaurant_open_time: 22,
    Restaurant_close_time: 10,
  },
  {
    image: "ten",
    name: "Red-Haired Tavern",
    rating: 1,
    food_type: "Tempura",
    Price_for_two: 1288,
    location: "Skypiea",
    Distance_from_Customer_house: "3.1",
    offers: 30,
    alcohol: true,
    Restaurant_open_time: 0,
    Restaurant_close_time: 12,
  },
  {
    image: "third",
    name: "Gear 5 Gastro",
    rating: 2,
    food_type: "Katsu Curry",
    Price_for_two: 1350,
    location: "Marineford",
    Distance_from_Customer_house: "7.2",
    offers: 19,
    alcohol: false,
    Restaurant_open_time: 2,
    Restaurant_close_time: 14,
  },
  {
    image: "fourth",
    name: "Sky Island Sweets",
    rating: 4,
    food_type: "Takoyaki",
    Price_for_two: 836,
    location: "Wano Country",
    Distance_from_Customer_house: "10.1",
    offers: 28,
    alcohol: false,
    Restaurant_open_time: 23,
    Restaurant_close_time: 11,
  },
  {
    image: "third",
    name: "Gomu Gomu Grill",
    rating: 5,
    food_type: "Okonomiyaki",
    Price_for_two: 359,
    location: "Sabaody Archipelago",
    Distance_from_Customer_house: "3.2",
    offers: 12,
    alcohol: false,
    Restaurant_open_time: 6,
    Restaurant_close_time: 18,
  },
  {
    image: "fifth",
    name: "Pirate King's Banquet",
    rating: 2,
    food_type: "Matcha Desserts",
    Price_for_two: 581,
    location: "Sabaody Archipelago",
    Distance_from_Customer_house: "4.1",
    offers: 8,
    alcohol: false,
    Restaurant_open_time: 14,
    Restaurant_close_time: 2,
  },
  {
    image: "fourth",
    name: "Raftel Resto",
    rating: 2,
    food_type: "Matcha Desserts",
    Price_for_two: 583,
    location: "Whole Cake Island",
    Distance_from_Customer_house: "1.5",
    offers: 3,
    alcohol: true,
    Restaurant_open_time: 14,
    Restaurant_close_time: 2,
  },
  {
    image: "second",
    name: "Luffy’s Meat Paradise",
    rating: 1,
    food_type: "Takoyaki",
    Price_for_two: 1268,
    location: "Raftel (Laughtale)",
    Distance_from_Customer_house: "9.7",
    offers: 19,
    alcohol: false,
    Restaurant_open_time: 6,
    Restaurant_close_time: 18,
  },
  {
    image: "fourth",
    name: "Sky Island Sweets",
    rating: 1,
    food_type: "Okonomiyaki",
    Price_for_two: 561,
    location: "Whole Cake Island",
    Distance_from_Customer_house: "3.1",
    offers: 21,
    alcohol: true,
    Restaurant_open_time: 20,
    Restaurant_close_time: 8,
  },
  {
    image: "nine",
    name: "Pirate King's Banquet",
    rating: 3,
    food_type: "Tempura",
    Price_for_two: 1696,
    location: "Skypiea",
    Distance_from_Customer_house: "9.3",
    offers: 19,
    alcohol: true,
    Restaurant_open_time: 13,
    Restaurant_close_time: 1,
  },
  {
    image: "fourth",
    name: "Yonko’s Feast",
    rating: 5,
    food_type: "Matcha Desserts",
    Price_for_two: 1056,
    location: "Dressrosa",
    Distance_from_Customer_house: "3.0",
    offers: 27,
    alcohol: false,
    Restaurant_open_time: 14,
    Restaurant_close_time: 2,
  },
  {
    image: "fourth",
    name: "Baratie Bites",
    rating: 1,
    food_type: "Tempura",
    Price_for_two: 2381,
    location: "Raftel (Laughtale)",
    Distance_from_Customer_house: "4.0",
    offers: 22,
    alcohol: true,
    Restaurant_open_time: 20,
    Restaurant_close_time: 8,
  },
  {
    image: "eight",
    name: "Gomu Gomu Grill",
    rating: 4,
    food_type: "Ramen",
    Price_for_two: 1941,
    location: "Whole Cake Island",
    Distance_from_Customer_house: "10.4",
    offers: 26,
    alcohol: false,
    Restaurant_open_time: 8,
    Restaurant_close_time: 20,
  },
  {
    image: "nine",
    name: "Grand Line Diner",
    rating: 2,
    food_type: "Tempura",
    Price_for_two: 2348,
    location: "Impel Down",
    Distance_from_Customer_house: "9.3",
    offers: 1,
    alcohol: false,
    Restaurant_open_time: 2,
    Restaurant_close_time: 14,
  },
  {
    image: "first",
    name: "Straw Hat Café",
    rating: 4,
    food_type: "Okonomiyaki",
    Price_for_two: 676,
    location: "Raftel (Laughtale)",
    Distance_from_Customer_house: "6.0",
    offers: 29,
    alcohol: true,
    Restaurant_open_time: 2,
    Restaurant_close_time: 14,
  },
  {
    image: "second",
    name: "Wano Ramen House",
    rating: 5,
    food_type: "Tempura",
    Price_for_two: 2133,
    location: "Raftel (Laughtale)",
    Distance_from_Customer_house: "3.7",
    offers: 4,
    alcohol: false,
    Restaurant_open_time: 13,
    Restaurant_close_time: 1,
  },
  {
    image: "fifth",
    name: "Devil Fruit Delights",
    rating: 1,
    food_type: "Takoyaki",
    Price_for_two: 184,
    location: "Impel Down",
    Distance_from_Customer_house: "6.2",
    offers: 28,
    alcohol: false,
    Restaurant_open_time: 16,
    Restaurant_close_time: 4,
  },
  {
    image: "seven",
    name: "Straw Hat Café",
    rating: 3,
    food_type: "Matcha Desserts",
    Price_for_two: 732,
    location: "Wano Country",
    Distance_from_Customer_house: "2.8",
    offers: 19,
    alcohol: true,
    Restaurant_open_time: 8,
    Restaurant_close_time: 20,
  },
  {
    image: "third",
    name: "Red-Haired Tavern",
    rating: 1,
    food_type: "Takoyaki",
    Price_for_two: 1131,
    location: "Raftel (Laughtale)",
    Distance_from_Customer_house: "6.9",
    offers: 3,
    alcohol: false,
    Restaurant_open_time: 22,
    Restaurant_close_time: 10,
  },
  {
    image: "fifth",
    name: "All Blue Kitchen",
    rating: 4,
    food_type: "Ramen",
    Price_for_two: 803,
    location: "Sabaody Archipelago",
    Distance_from_Customer_house: "1.3",
    offers: 7,
    alcohol: true,
    Restaurant_open_time: 14,
    Restaurant_close_time: 2,
  },
  {
    image: "third",
    name: "Sunny Feast",
    rating: 1,
    food_type: "Ramen",
    Price_for_two: 2141,
    location: "Dressrosa",
    Distance_from_Customer_house: "7.3",
    offers: 30,
    alcohol: false,
    Restaurant_open_time: 14,
    Restaurant_close_time: 2,
  },
  {
    image: "fourth",
    name: "Devil Fruit Delights",
    rating: 4,
    food_type: "Udon",
    Price_for_two: 141,
    location: "Foosha Village",
    Distance_from_Customer_house: "2.2",
    offers: 16,
    alcohol: false,
    Restaurant_open_time: 20,
    Restaurant_close_time: 8,
  },
  {
    image: "seven",
    name: "Sanji’s Gourmet Haven",
    rating: 2,
    food_type: "Katsu Curry",
    Price_for_two: 1068,
    location: "Whole Cake Island",
    Distance_from_Customer_house: "3.2",
    offers: 0,
    alcohol: false,
    Restaurant_open_time: 11,
    Restaurant_close_time: 23,
  },
  {
    image: "fifth",
    name: "Raftel Resto",
    rating: 2,
    food_type: "Matcha Desserts",
    Price_for_two: 1607,
    location: "Water 7",
    Distance_from_Customer_house: "5.2",
    offers: 0,
    alcohol: true,
    Restaurant_open_time: 21,
    Restaurant_close_time: 9,
  },
  {
    image: "eight",
    name: "Sky Island Sweets",
    rating: 1,
    food_type: "Sushi",
    Price_for_two: 938,
    location: "Raftel (Laughtale)",
    Distance_from_Customer_house: "1.9",
    offers: 0,
    alcohol: false,
    Restaurant_open_time: 20,
    Restaurant_close_time: 8,
  },
  {
    image: "third",
    name: "Red-Haired Tavern",
    rating: 4,
    food_type: "Okonomiyaki",
    Price_for_two: 1626,
    location: "Whole Cake Island",
    Distance_from_Customer_house: "3.8",
    offers: 10,
    alcohol: false,
    Restaurant_open_time: 2,
    Restaurant_close_time: 14,
  },
  {
    image: "fifth",
    name: "Raftel Resto",
    rating: 1,
    food_type: "Ramen",
    Price_for_two: 1054,
    location: "Foosha Village",
    Distance_from_Customer_house: "4.7",
    offers: 10,
    alcohol: false,
    Restaurant_open_time: 20,
    Restaurant_close_time: 8,
  },
  {
    image: "third",
    name: "Straw Hat Café",
    rating: 2,
    food_type: "Takoyaki",
    Price_for_two: 2182,
    location: "Water 7",
    Distance_from_Customer_house: "5.2",
    offers: 0,
    alcohol: false,
    Restaurant_open_time: 6,
    Restaurant_close_time: 18,
  },
  {
    image: "first",
    name: "Pirate King's Banquet",
    rating: 4,
    food_type: "Matcha Desserts",
    Price_for_two: 1804,
    location: "Foosha Village",
    Distance_from_Customer_house: "9.1",
    offers: 24,
    alcohol: false,
    Restaurant_open_time: 3,
    Restaurant_close_time: 15,
  },
  {
    image: "ten",
    name: "Baratie Bites",
    rating: 1,
    food_type: "Okonomiyaki",
    Price_for_two: 2035,
    location: "Raftel (Laughtale)",
    Distance_from_Customer_house: "4.5",
    offers: 24,
    alcohol: false,
    Restaurant_open_time: 6,
    Restaurant_close_time: 18,
  },
];

function getrestaurant(restaurants) {
  const root = document.getElementById("root");
  restaurants.forEach((restaurants) => {
    // create a card div ->
    // 1: Image
    /* 2: card contant -> div
    1: div -> card_header div ->  {name,rating}
    2: div -> card_footer  div -> {foodtype and price}
    3: div -> card_location div ->  {restaurant_location , distance}
    
    */

    // create a card div
    const card = document.createElement("div");
    card.classList.add("card"); //giving class name .card

    // create Image
    const image = document.createElement("img");
    image.src = `photos/${restaurants.image}.jpg`;

    // card content
    const Card_content = document.createElement("div");
    Card_content.classList.add("card-content");

    //card header
    const Card_header = document.createElement("div");
    Card_header.classList.add("card-header");

    const h3 = document.createElement("h3");
    h3.textContent = restaurants.name;

    const rate = document.createElement("span");
    rate.textContent = "Rating: " + restaurants.rating;
    rate.classList.add("rating"); // Add the class for styling

    Card_header.appendChild(h3);
    Card_header.appendChild(rate);

    //card footer
    const Card_footer = document.createElement("div");
    Card_footer.classList.add("card-footer");

    const food = document.createElement("span");
    food.textContent = restaurants.food_type;

    const price = document.createElement("span");
    price.textContent = "₹" + restaurants.Price_for_two;

    Card_footer.appendChild(food);
    Card_footer.appendChild(price);

    //card location
    const Card_location = document.createElement("div");
    Card_location.classList.add("card-location"); //class list se multiple class assign kr skte h

    const location = document.createElement("span");
    location.textContent = restaurants.location;

    const distance = document.createElement("span");
    distance.textContent = restaurants.Distance_from_Customer_house + "km";

    Card_location.appendChild(location);
    Card_location.appendChild(distance);

    Card_content.appendChild(Card_header);
    Card_content.appendChild(Card_footer);
    Card_content.appendChild(Card_location);

    card.appendChild(image);
    card.appendChild(Card_content);

    root.appendChild(card);
  });
}
getrestaurant(restaurants);

// step 2
document.getElementById("Alcohol").addEventListener("click", () => {
  const result = restaurants.filter((obj) => obj.alcohol); //if its true it will select all true value

  // document.getElementById("root").innerHTML = ""; //phle inner html ko khali kro
  //  or
  document.getElementById("root").replaceChildren(); //phle inner html ko khali kro
  getrestaurant(result);
});

// step 3
document.getElementById("Rating").addEventListener("click", () => {
  const result = restaurants.filter((obj) => obj.rating > 4.5); //if its true it will select all true value

  // document.getElementById("root").innerHTML = ""; //phle inner html ko khali kro
  //  or
  document.getElementById("root").replaceChildren(); //phle inner html ko khali kro
  getrestaurant(result);
});

// step 4
document.getElementById("Offers").addEventListener("click", () => {
  const result = restaurants.filter((obj) => obj.offers > 20); //if its true it will select all true value

  // document.getElementById("root").innerHTML = ""; //phle inner html ko khali kro
  //  or
  document.getElementById("root").replaceChildren(); //phle inner html ko khali kro
  getrestaurant(result);
});

// step 5
document.getElementById("Open").addEventListener("click", () => {
  const result = restaurants.filter(
    (obj) => obj.Restaurant_open_time > 7 && obj.Restaurant_open_time <= 12
  ); //if its true it will select all true value

  // document.getElementById("root").innerHTML = ""; //phle inner html ko khali kro
  //  or
  document.getElementById("root").replaceChildren(); //phle inner html ko khali kro
  getrestaurant(result);
});

// step 6
document.getElementById("Filters").addEventListener("click", () => {
  document.getElementById("filterPopup").classList.remove("hidden");
});

document.getElementById("applyFilter").addEventListener("click", () => {
  const selectedFilter = document.querySelector(
    'input[name="filterOption"]:checked'
  );

  // if (!selectedFilter) {
  //   console.log("No filter selected");
  //   return;
  // }

  const ans = selectedFilter.value;

  if (ans == "rating") {
    restaurants.sort((a, b) => b.rating - a.rating); // Descending order
  } else if (ans == "highLow") {
    restaurants.sort((a, b) => b.Price_for_two - a.Price_for_two);
  } else if (ans == "costLowHigh") {
    // Fixed comparison operator
    restaurants.sort((a, b) => a.Price_for_two - b.Price_for_two);
  } else if (ans == "distance") {
    restaurants.sort(
      (a, b) => a.Distance_from_Customer_house - b.Distance_from_Customer_house
    );
  }

  document.getElementById("root").replaceChildren(); // Clear previous results
  document.getElementById("filterPopup").classList.add("hidden");
  getrestaurant(restaurants); // Display sorted results
});

document.getElementById("closeFilter").addEventListener("click", () => {
  document.getElementById("root").replaceChildren(); // Clear previous results
  document.getElementById("filterPopup").classList.add("hidden");
  getrestaurant(restaurants); // Display sorted results
});
